# Development environment override
services:
  backend:
    build:
      context: ./infrastructure/backend
      target: backend_dev
    volumes:
      - ./backend:/app
      - ./infrastructure/backend/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./infrastructure/backend/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - /app/var
      - /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

  frontend:
    build:
      context: ./infrastructure/frontend
      target: frontend_dev
    volumes:
      - ./frontend:/srv/app
    environment:
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
