# Production environment override
services:
  backend:
    build:
      context: ./backend
      target: backend_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  frontend:
    build:
      context: ./frontend
      target: frontend_prod

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
